{{- range $name, $cfg := .Values.roles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-pg-creds
  labels:
    app: pg-shared
type: kubernetes.io/basic-auth
stringData:
  username: {{ $name | quote }}
  password: {{ $cfg.password | quote }}
{{- end }}
