apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  labels:
    app: immich
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "immich.cute.haus"
      secretName: cute-haus-tls
  rules:
    - host: "immich.cute.haus"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich
                port:
                  number: 80
