{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: immich-env
  labels:
    app: immich
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-config
  labels:
    app: immich
type: Opaque
stringData:
  config.json: |
    {
      "oauth": {
        "enabled": true,
        "issuerUrl": "https://id.cute.haus",
        "clientId": {{ .Values.secret.oauthClientId | toJson }},
        "clientSecret": {{ .Values.secret.oauthClientSecret | toJson }},
        "scope": "openid email profile",
        "buttonText": "Sign in with cute.haus",
        "autoRegister": true,
        "autoLaunch": false,
        "mobileOverrideEnabled": false,
        "mobileRedirectUri": ""
      },
      "passwordLogin": {
        "enabled": false
      }
    }
{{- end }}
