repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: 40.0.0
    values:
      - deployment:
          kind: DaemonSet
        service:
          type: ClusterIP
        ports:
          web:
            hostPort: 80
          websecure:
            hostPort: 443
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        priorityClassName: system-cluster-critical
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true

  - name: aly-codes
    namespace: default
    chart: ./charts/aly-codes

  - name: watsup
    namespace: default
    chart: ./charts/watsup

  - name: external-routes
    namespace: default
    chart: ./charts/external-routes
