repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 32.1.1
    values:
      - deployment:
          kind: DaemonSet
        service:
          type: ClusterIP
        ports:
          web:
            hostPort: 80
          websecure:
            hostPort: 443
        nodeSelector:
          kubernetes.io/hostname: solaceon
        ingressClass:
          enabled: true
          isDefaultClass: true

  - name: aly-codes
    namespace: default
    chart: ./charts/aly-codes

  - name: watsup
    namespace: default
    chart: ./charts/watsup

  - name: external-routes
    namespace: default
    chart: ./charts/external-routes
