apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: jellyfin-creds
type: Opaque
stringData:
  RCLONE_CONFIG_B2_TYPE: b2
  RCLONE_CONFIG_B2_ACCOUNT: {{ .Values.secret.keyId | quote }}
  RCLONE_CONFIG_B2_KEY: {{ .Values.secret.appKey | quote }}
  RCLONE_CONFIG_COMBINED_TYPE: combine
  RCLONE_CONFIG_COMBINED_UPSTREAMS: {{ .Values.secret.upstreams | quote }}
