apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helmrepositories.yaml
configMapGenerator:
  - name: cute-haus-global
    files:
      - values.yaml=global.values.yaml
    options:
      disableNameSuffixHash: true
      annotations:
        cute.haus/secret-policy: non-secret-values-only
