replicaCount: 2

dnsPolicy: Default

image:
  repository: ghcr.io/alyraffauf/watsup
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 8383

ingress:
  enabled: false
  className: nginx
  host: cute.haus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
