replicaCount: 2

dnsPolicy: Default

image:
  repository: ghcr.io/alyraffauf/watsup
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  hosts:
    - cute.haus
    - www.cute.haus
  tls:
    - hosts:
        - cute.haus
        - www.cute.haus
      secretName: cute-haus-tls
