{{- range $name, $tls := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-tls
  labels:
    app: cluster-tls
type: kubernetes.io/tls
stringData:
  tls.crt: {{ $tls.crt | quote }}
  tls.key: {{ $tls.key | quote }}
{{- end }}
