{{- range $route := .Values.routes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $route.name }}
  labels:
    app: {{ $route.name }}
spec:
  ports:
    - port: {{ $route.target.port }}
      protocol: TCP
      targetPort: {{ $route.target.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $route.name }}   # must match Service name
  labels:
    app: {{ $route.name }}
subsets:
  - addresses:
      - ip: {{ $route.target.ip }}
    ports:
      - port: {{ $route.target.port }}
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $route.name }}
  labels:
    app: {{ $route.name }}
spec:
  ingressClassName: {{ $.Values.ingressClassName }}
  {{- $hosts := prepend (default (list) $route.aliases) $route.host }}
  {{- if $route.tls }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ $route.tls.secretName }}
  {{- end }}
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $route.name }}
                port:
                  number: {{ $route.target.port }}
    {{- end }}
{{- end }}
