apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFromSecret }}
  labels:
    app: bluesky-pds
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
