replicaCount: 1

image:
  repository: caddy
  tag: "2"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: NodePort
  port: 443
  nodePort: 8443

tls:
  secretName: cute-haus-tls

caddyfile: |
  {
    admin off
    auto_https off
  }

  cute.haus, www.cute.haus {
    tls /etc/caddy/tls/tls.crt /etc/caddy/tls/tls.key
    encode zstd gzip
    reverse_proxy http://watsup-svc.default.svc.cluster.local:80
  }
