- hosts: eterna
  remote_user: root

  tasks:
    - name: Restart podman-atbbs
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: restarted
      loop:
        - podman-atbbs
        - podman-atbbs-telnet
