apiVersion: apps/v1
kind: Deployment
metadata:
  name: watsup
  labels:
    app: watsup
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: watsup
  template:
    metadata:
      labels:
        app: watsup
    spec:
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      containers:
        - name: watsup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
