secret:
  aly-codes:
    crt: ref+sops://../secrets/cluster-tls.yaml#/secret/aly-codes/crt
    key: ref+sops://../secrets/cluster-tls.yaml#/secret/aly-codes/key
  aly-social:
    crt: ref+sops://../secrets/cluster-tls.yaml#/secret/aly-social/crt
    key: ref+sops://../secrets/cluster-tls.yaml#/secret/aly-social/key
  morsels-blue:
    crt: ref+sops://../secrets/cluster-tls.yaml#/secret/morsels-blue/crt
    key: ref+sops://../secrets/cluster-tls.yaml#/secret/morsels-blue/key
