secret:
  dbPassword: ref+sops://../secrets/immich.yaml#/db/password
  oauthClientId: ref+sops://../secrets/immich.yaml#/oauth/client_id
  oauthClientSecret: ref+sops://../secrets/immich.yaml#/oauth/client_secret
