secret:
  JWT_SECRET: ref+sops://../secrets/tranquil-pds.yaml#/secret/JWT_SECRET
  DPOP_SECRET: ref+sops://../secrets/tranquil-pds.yaml#/secret/DPOP_SECRET
  MASTER_KEY: ref+sops://../secrets/tranquil-pds.yaml#/secret/MASTER_KEY
  DATABASE_URL: ref+sops://../secrets/pg-roles.yaml#/roles/tranquil/url
  MAIL_SMARTHOST_PASSWORD: ref+sops://../secrets/tranquil-pds.yaml#/secret/MAIL_SMARTHOST_PASSWORD
  AWS_ACCESS_KEY_ID: ref+sops://../secrets/b2.yaml#/B2_KEY_ID
  AWS_SECRET_ACCESS_KEY: ref+sops://../secrets/b2.yaml#/B2_APP_KEY

pullSecret:
  username: ref+sops://../secrets/atcr.yaml#/username
  password: ref+sops://../secrets/atcr.yaml#/password
