{{- if .Values.tailnet.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: {{ .Values.tailnet.proxyClass.name }}
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ .Values.tailnet.affinity.matchLabels.app }}
              namespaces:
                {{- range .Values.tailnet.affinity.namespaces }}
                - {{ . }}
                {{- end }}
              topologyKey: kubernetes.io/hostname
{{- end }}
