{{- if .Values.tailnet.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tailnet.ingressName }}
  labels:
    app: longhorn-creds
    tailscale.com/proxy-class: {{ .Values.tailnet.proxyClass.name }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.tailnet.hostname }}
  defaultBackend:
    service:
      name: {{ .Values.tailnet.serviceName }}
      port:
        number: {{ .Values.tailnet.servicePort }}
{{- end }}
