{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: navidrome-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  navidrome.env: {{ .Values.secret.env | quote }}
{{- end }}
